#!/usr/bin/env bash
# Bash script that will display information about the subdomains

dns_config () {
    record=$(dig "$2"."$1" +short)
    if [ -z "$record" ]; then
        echo "The subdomain $2 does not have an A record."
    else
        echo "The subdomain $2 is an A record and points to $record"
    fi
}

if [ "$#" -eq 1 ]; then
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  dns_config "$1" "$2"
else
  echo "Usage: $0 <domain> [subdomain]"
fi
